MONGODB_HOST: mongodb-{{ env }}.piridishop.shop
REDIS_HOST: redis-{{ env }}.piridishop.shop
MYSQL_HOST: mysql-{{ env }}.piridishop.shop 
RABBITMQ_HOST: rabbitmq-{{ env }}.piridishop.shop 
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.piridishop.shop
USER_HOST: user.backend-alb-{{ env }}.piridishop.shop
CART_HOST: cart.backend-alb-{{ env }}.piridishop.shop
SHIPPING_HOST: shipping.backend-alb-{{ env }}.piridishop.shop
PAYMENT_HOST: payment.backend-alb-{{ env }}.piridishop.shop
